// This file holds the actual content of our model essays: the
// question each one answers, its topic, its grade (if known), and
// the cleaned essay text (OCR/transcription errors corrected).
//
// HOW TO ADD MORE ESSAYS: copy one of the objects below, fill in
// your own values, and add it to the modelEssays array. The seed
// script (seedModelEssays.ts) will automatically pick up any new
// entries the next time it runs.

export type ModelEssayInput = {
  questionText: string;
  topicCategory:
    | "Society & Culture"
    | "Economics"
    | "Politics"
    | "Arts & Humanities"
    | "Science & Technology"
    | "Environment";
  gradeScore: number | null;
  qualityLabel: "graded" | "expected_high_band";
  essayText: string;
};

export const modelEssays: ModelEssayInput[] = [
  {
    questionText: `"Sheltered and entitled." Is this fair criticism of youth today?`,
    topicCategory: "Society & Culture",
    gradeScore: 31,
    qualityLabel: "graded",
    essayText: `Sheltered and entitled. A phrase now so commonly used to label the youth of today. It is not atypical to see older generations lament on how teenagers have gone soft, contrasting their hard lives during arduous times of war with the privilege we now face. While they may be isolated cases that support this narrative, applying this label broadly is unfair and dismissive. In truth, today's youth are navigating an increasingly complex world, demonstrating resilience, social consciousness, and adaptability that often goes unrecognized.

The idea that today's youth are sheltered fails to recognize the difficult realities they regularly face. More than ever, awareness on a myriad of different issues is on the rise. Concerns on social equity, economic inequality, human rights, climate change, etcetera, have all been brought to the light. Unlike earlier generations, young people today grew up in a world filled with constant exposure to social issues and global crises, especially with twenty four seven news, social media and online platforms, youth are constantly informed about the climate change they face, the political conflict that affects them, and mental health challenges that we have. In fact, a twenty twenty three Pew Research study showed over seventy percent of teens reported anxiety related to global issues like climate change and economic instability. Is this the works of a sheltered generation? This demonstrates that far from being protected or naive, young people are acutely aware of the world's problems, and must develop coping mechanisms early in life.

Advocacy may oftentimes be misinterpreted as entitlement. Older generations may criticize the youth stating that we have too many problems overcomplicating our lives. This misunderstands youth advocacy as selfishness rather than empowerment, overlooking the deeper motivations behind a desire for meaningful change. In fact, many young people voice out their concerns about climate change, mental health, and racial justice not in a ploy to receive special treatment but because they believe in building a more just and sustainable future for themselves and others. Movements like Fridays for Future, led by youth activist Greta Thunberg, as well as mental health advocacy on platforms like Instagram and TikTok are largely youth driven and aim to address issues that affect entire communities. Rather than entitlement, this shows a sense of independence that comes from the willingness to step up and evoke a change in what one believes as rights. This increased sense of proactiveness has shown its ability to unite society and galvanize others towards a social cause. UNICEF has even reported in twenty twenty three that nearly sixty percent of youth globally have participated in some form of social or environmental activism. Aside from labeling this as being entitled, it should be recognized as a sign of empowerment and empathy along with a willingness to take responsibility for shaping the world they will inherit.

However, despite the strength of today's youth, it is important that we recognize instances of overdependence. Overprotective, or "helicopter parenting," is a term used to describe parents nowadays where they are excessively involved in their child's experiences, often intervening to a degree of excessiveness just to prevent any sliver of failure, discomfort, or conflict. While such behavior may stem from good intentions, it inadvertently deprives children of opportunities to develop independence, problem solving skills, and emotional resilience. In fact, psychologist Jean Twenge stated a decline in unstructured independent experiences has led to an increased level of anxiety and could reduce coping skills among adolescents. While this critique holds some merit, it should be understood as a symptom of broader societal shifts, rather than an inherent flaw in the youth themselves. More importantly, it does not negate the resilience and agency many young people display across a multitude of domains.

Besides, today's youth have demonstrated remarkable adaptability and innovation to this rapidly changing world. Compared to members of the older generation, young people have not only adapted to technological change, but they have also leveraged it to create new forms of work, learning, and activism. A prime showcase of this was during the COVID-19 pandemic, where we saw many young individuals start online businesses and produce accessible, educational content on social media platforms. In accordance with a twenty twenty two Shopify report, Gen Z accounted for a significant share of new entrepreneurial activity during the pandemic, using their digital tools to patch gaps found in traditionalistic systems. Such actions reflect a proactive mindset and the ability to innovate under pressure, qualities that run counter to the narrative of "sheltered and entitled" associated with youth.

In conclusion, labeling today's youth as sheltered and entitled is an oversimplification that completely overlooks their complexities and contributions. While it is valid to acknowledge areas where resilience and independence could be better fostered, it is equally important to recognize the pressures and challenges the youth face today as leaders and inhabitants of the future, which should encourage us to support and collaborate with the youth rather than spend time criticizing and bringing down what lies ahead.`,
  },
  {
    questionText: `The internet has become a hotbed of lies and misguided notions. Comment.`,
    topicCategory: "Science & Technology",
    gradeScore: 29,
    qualityLabel: "graded",
    essayText: `The internet has many a time been held as the greatest information resource of the twenty first century and has revolutionized the way we communicate and the information that we take in. By design or not, this evidently affects how the masses are influenced. While it connects people globally and democratizes knowledge, its open and public nature also allows for the proliferation of falsehoods and harmful ideas. The anonymity of the internet and social media further threatens to make the internet a hotbed of lies and misguided notions.

The danger of the internet lies within users being fed with false information under the guise of it being true. This begins by way of filter bubbles on online media platforms, and their pervasive influence creates echo chambers where users are inundated with information that supports their preexisting views and are thus underexposed to information that challenges their assumptions. This effectively isolates them in their own cultural or ideological bubbles. According to research by Pew Research Center, forty seven percent of conservatives in the United States of America were likely to see Facebook posts aligned with their own views, as opposed to half that percentage for those who were neutral. This form of filtering is rather worrisome because it affirms the user's confirmation bias, creating the impression that only one correct stance, theirs, exists. This may manifest in a breeding ground for falsehoods and lies as individuals are not exposed to other narratives which may challenge their own.

This could also come by way of the online algorithm itself. Many social media platforms and internet platforms have an inner algorithm that suggests posts to users on the basis of engagement. This engagement comes in the form of likes, shares, and reposts, which then send a signal to the algorithm to push out the post so that more people get to see it. When we come across a new piece of information, our brain decides whether or not to believe it. If the new information agrees with our existing beliefs, we buy into it automatically, and in the case of social media, we will then like, subscribe, and share such articles that fit our belief systems. If one individual strongly believes that a blatant lie is true, he ends up sharing that lie to the people around him, and this causes a trickle down effect as long as people are not cautious enough to verify it for themselves. We have seen this come up during the COVID-19 pandemic. During this time, false claims about vaccines and treatments flooded the internet, creating confusion, undermining public health efforts, and ultimately creating fear and panic where there was no need for it. Similarly, political misinformation has fueled division and distrust, with fake news influencing elections and polarizing societies.

However, labeling the internet solely as a hotbed of lies overlooks its immense value. The same platform that spreads misinformation also provides tools for education, activism, and global collaboration. Information is now easily accessible, with verified sources of knowledge like academic journals, news outlets, and educational platforms freely available to anyone with an internet connection. Moreover, the internet has democratized knowledge in a never before seen fashion. It empowers individuals, providing marginalized voices a platform to express themselves, facilitating movements for social justice and change, and we have seen this happen in protests such as the MeToo movement. Even as we speak, communities in the USA are protesting against the inauguration of their president online.

Yet the anonymity and ease of exchange of the internet may further exacerbate this issue. Users spread falsehoods without accountability, and the ease of sharing such misinformation leads to misguided ideas flourishing unchecked. This has led to the emergence of "keyboard warriors," used to describe users who take advantage of this anonymity, freely posting whatever they wish online knowing they are unlikely to face consequences from it. Such individuals treat their devices like a veil to hide their faces and utilize it to spread lies and falsehoods, many a time without even believing such ideas. In the case that they do, they try their best to push their agendas in whatever way they are able to do so. One prominent example of this is the Pizzagate conspiracy theory in 2016 during the US presidential elections. Alt-right users on the far end of the political spectrum began spreading false claims that a Washington DC pizzeria, Comet Ping Pong, was the hub of a child trafficking ring allegedly run by members of Hillary Clinton's campaign. This conspiracy theory, although purely absurd, quickly garnered traction on social media platforms, with anonymous users sharing fabricated stories, doctoring images, and unfounded allegations. The anonymity of those spreading the conspiracy made it difficult to trace the origins of the misinformation, and it even had real world consequences when a man, Edgar Welch, showed up at the pizzeria with a gun, claiming he was there to investigate and rescue the alleged victims, despite the claims being entirely baseless. The conspiracy showcased how anonymity allows falsehoods to spread unchecked, creating real harm and endangering lives.

The internet can indeed be a hotbed of lies and misguided notions, but it is also a powerful tool for truth and progress. The challenge lies in mitigating its risks while maximizing its potential. A completely unregulated internet left free to the people is inevitably detrimental to society, as misinformation will quickly plague the masses. However, while each society is fighting its own battles, facts against fiction, democracy against autocracy, it is paramount that we accept what we read online sparingly and use resources to fact check. Only this way can we maintain the volatile social fabric of our societies and keep the internet from distorting our view of reality.`,
  },
  {
    questionText: `"It is not worth the trouble for countries to host major sporting events." To what extent is this good advice?`,
    topicCategory: "Economics",
    gradeScore: 32,
    qualityLabel: "graded",
    essayText: `When one mentions major sporting events, what typically comes to mind are events such as the Olympics or the Southeast Asian Games. Not only are such events internationally acclaimed, it is an honor to be selected as a host country for them. However, it takes extensive infrastructure, financial resources, and manpower to invest into it, such that more often than not, when less developed countries are unable to bear such costs, it becomes a burden towards a nation and its economy. Yet, it would be false to claim that generally such events do not bring major benefits to a country, namely in the economic and social sectors, to the extent that it would be better advice if it were not worth the trouble for countries to host major sporting events.

Obviously, for any country, hosting events such as the Olympics is bound to bring some economic returns. With thousands of the world's best athletes competing for a world title, people are definitely going to be interested, and through ticket sales and a significant boost in tourism, countries are able to earn a large sum of revenue. With an influx of tourists, sales for restaurants, hotels, and even entertainment will all rise exponentially. Besides, nations hosting major sporting events often receive funds from the International Olympic Committee which are channeled into the renovation of a country in order to adequately prepare it for such an event. All of this makes it all the more attractive for any country to attain the opportunity to host the Olympics.

However, for less developed countries, the economic benefits of hosting a global sporting event are often eclipsed by underestimated costs that already sizable local budgets fail to keep up with. Since 1960, every Olympic Games event has exceeded its budget by an average of one hundred and seventy two percent in inflation adjusted terms according to research findings by Oxford University, even exceeding investments in key infrastructure such as transportation. As a result, for less developed countries, their national budget simply cannot withstand this heavy blow on their economy. And when funding for event related infrastructure begins to eat into their funding for social welfare, it can lead to the complete weakening of a country's economy and its governance. Herein lies the trouble in hosting such events.

Hosting major sporting events can also have significant social impacts. These events help foster a sense of national pride and unity as competitors and interested onlookers root for their countries in hopes of winning and being the best nation in a particular sport. In attaining the status of an Olympic gold medalist, such a title brings immense joy and pride not only to the athlete themselves but also the wider community of people that stood together as one to support and cheer on for their own nation. Such events also bring individuals of diverse backgrounds together, even if they are from separate countries. When viewers watch the Olympics live in a stadium or at a nearby bar, they are surrounded by many of their fellow countrymen as well as many in opposing competition. This makes it easy to bond over friendly competition with others from all walks of life, each individual transforming into their own country's representative patriot, cheering on national athletes to win.

Yet it would be foolish to think that such an event would not bring negative social impacts too. A recent example is when Qatar hosted the World Cup. There have been many reports of unsafe working conditions, long hours, and inadequate pay. There have even been deaths occurring as a result of migrant workers toiling to build infrastructure for the World Cup. This helped shed light on human rights violations and the exploitation of workers that occur behind the apparent glamour of such events.

Yet, legacy is a key factor which makes it worth the trouble for countries to host major sporting events. Such events give rise to countries having the rare opportunity to showcase their culture and what they have to offer, from the first Olympics in Athens to the 2024 Paris Olympics that just happened, with your name etched forever next to the most prestigious and widely regarded as the most populated and difficult competition in the world, as a once in a lifetime opportunity. China displayed a stunning performance at the opening ceremony of the 2008 Beijing Olympics, where they then proceeded to attain the most number of gold medals in the event overall. Such stellar performances not only put certain countries on the map, they boost the international standing and influence international opinions. As an event that occurs typically once every four years, countries are given the rare opportunity to make the event legendary and memorable. Investing endless amounts of cash is not what gets a country global recognition, and since money is a limited resource, technically, nor is the potential risk to social welfare. Thus, the potential to leave an unforgettable legacy makes it worthwhile all the troubles a country potentially undergoes.

In conclusion, I would say that to claim it is not worth the trouble for countries to host major sporting events is, to a little extent, good advice, and is instead largely bad advice. If such a thing were true, there would be no reason for the Olympics to exist, let alone for any country to attempt hosting it. Yet host countries for the Olympics have been confirmed up to even 2032. On the other hand, it is not to say that hosting the Olympics is void of its own fair share of negative impacts, as discussed in the economic and social aspects. Thus, it is important to note that only countries willing and able to bear potential costs of underestimation, of course, to social welfare should be allowed to host the Olympics, until a less developed country is certain it can prove it is able to do so, preventing the country from going into unforeseeable economic debt. Besides, such negative impacts are fairly easy to avoid, should a country take more caution and time into carefully planning and leaving more leeway in the budget. The legacy a country can potentially leave behind can heavily outweigh such impacts, so long as a country is able to bear it. All in all, to generally say that it is not worth the trouble for countries to host major sporting events is bad advice, yet to minimize potential negative impacts, lesser developed nations should stay away from hosting them.`,
  },
  {
    questionText: `Environmental sustainability is unattainable for the poor. Discuss.`,
    topicCategory: "Environment",
    gradeScore: 29,
    qualityLabel: "graded",
    essayText: `Money runs the world, a common sentiment shared by many, that with money you can do a lot more than without it, even if you had the passion to do so. As richer countries dump more and more resources into financing the advancements of technology, while simultaneously global temperatures rise year by year, the poor are left stuck in an awkward position: to pursue the development of their own economy, or to care for the environment. Unfortunately, if global superpowers are not willing to put their best foot forward, I find it difficult for us to expect that a push should come from any level of society. I do believe that when we refer to the poor as concerning developing countries, their efforts contrasted with the developed truly causes me to believe that environmental sustainability is unattainable for the poor.

When we refer to the poor, I believe we can start at the international scale. Environmental sustainability has been a hot topic of discussion among countries all over the world, with international treaties such as the Paris Climate Accord or the Kyoto Protocol seeing over a hundred countries banding together, pledging to strengthen conservation efforts. However, the truth of the matter is that richer countries contribute significantly more towards environmental degradation than poor developing countries. In fact, ninety percent of greenhouse gas emissions are produced by the top one percent of countries in the world. While the rich seem to be able to enjoy the pursuit of economic growth, the poor are left expected to honor agreements on environmental efforts, stagnating their own progress, especially when even global powerhouses like the United States of America refuse to pledge to environmental treaties, such as when Donald Trump decided to pull out of the Paris Climate Accord in 2017. This sets a bad precedent and sends the message that if even the USA does not want to help the environment, why should smaller nations? Especially considering that the environment is never the main priority for any government, it tells poorer countries that the opportunity cost of targeting conservation efforts is too high, and since countries that have the means to do so are not doing so, there must be no need for it. Hence, given the rich refuse to pledge to environmental sustainability, this goal gets further and more idealistic for the poor.

Besides, not only do the rich have the noblesse oblige to be more sustainable, on the basis that privilege begets responsibility, they also have the financial means to do so. As the world ages, new and more effective technology gets invented. However, as with most things in life, technology is not free. Even though the USA may not want to uphold environmental sustainability in the Paris Agreement, it still has the financial capital to otherwise invest in environmental technology for its own sake. We have seen this in investments in solar geoengineering, or even carbon capture technology, of which they are currently using to store close to fifty million tons of carbon emissions underground. Even in countries like Singapore, million dollar investments into infrastructure like solar panels, and even investment into vertical farming, literally farming upwards and not outwards, are all efforts towards environmental sustainability that countries cannot attain without capital. With such advanced technology available to aid in conservation efforts, the rich gain an advantage in this race to environmental sustainability.

But what about the poor? We could go on and on about how the rich and developed countries have come up with wonderful innovations that revolutionized one way or another, things like Germany's Energiewende and many more. But these methods are costly. When was the last time you heard of some rural village in remote Nigeria that came up with a revolutionary way that contributes more to environmental sustainability than what already exists? This is simply because they have more pressing issues to care about. When Gambia's president quite controversially said "LGBT" stands for "leprosy, gonorrhea, bacteria, and tuberculosis," albeit outrageous, this was proof that the poor are facing worse issues than any of the rich are. Such countries are already pouring and extending their limits towards alleviating atrocities that directly affect their people. Yet we still expect them to pour their resources into environmental sustainability, when, coupled with the previous point on how the superpowers are not even willing to keep to conservation efforts even when they are massively the reason behind this degradation, the poor are doomed to fail, akin to Sisyphus rolling his stone up a never ending hill. The poor are left never able to achieve the growth of their country nor environmental sustainability.

However, it is common to see people say that being kind to the environment is free, after all, prevention is better than cure. Individuals can start with their own actions, such as turning off overrunning taps, turning off light switches, and so on. After all, if everyone chips in, little by little, the chain of people banding together to help will cause massive change in our efforts, right? Unfortunately, I believe such notions are extremely performative. Though we say individual action is a very real factor that contributes to environmental degradation, it is the work of corporations and governments that largely outweighs any positive effects we are able to make. The construction of iPhones across the world alone generates millions of tons of carbon emissions. Imagine telling a starving mother in Africa with her children to turn off a water tap, granted she even has one, because she's "wasting water." How upsetting would that be? They simply have more worrisome issues to care about, something many of these "hashtag save the planet" influencers do not understand. Of course, it would be ignorant to say individual action does not galvanize change in any way, but I believe it all the more makes environmental sustainability even more of a tall order for the poor.

In conclusion, I believe that it is nearly impossible to expect the poor to achieve environmental sustainability. The first priority of a government should always be to advance its economy to gain position on the global stage, but this is difficult to balance with environmental sustainability due to the nature of technological advancement requiring a depletion of resources in the first place. Countries in East Asia experience exactly this, where even though they collectively grew eighty five percent as an economy, research reported that they instead contributed a hundred and eighty five percent more in detrimental emissions. Furthermore, the attitudes of the rich, coupled with the threat of more devastating complications, disincentivize the poor from even wanting to begin to be environmentally sustainable. Even if they wanted to, they simply may not have the funds to invest in any technology that would make any significant nor lasting effect on conservation efforts. If global superpowers are not willing to pick up the mantle now and change for the better, environmental sustainability will be realised as more and more of an unattainable goal for both the rich and the poor.`,
  },
];
